# CONFIGMAP FOR CLUSTER SPECIFIC VARIABLES

apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-vars
  namespace: flux-system
data:
  podinfoReplicas: "3"
  podinfoMessage: "Hello from sjc1"
  podinfoMemoryRequest: "16Mi"
  podinfoRedisURL: "redis://podinfo-redis:6379"
  podinfoRedisEnabled: "true"
  podinfoColor: "#FF0000"
