
# CONFIGMAP FOR GLOBAL VARIABLES APPLICABLE TO ALL CLUSTERS IN THIS CLUSTER GROUP
apiVersion: v1
kind: ConfigMap
metadata:
  name: global-vars
  namespace: flux-system
data:
  podinfoCpuRequest: "50m"
