apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: blueprints
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://github.com/ahothan/flux-blueprints.git
  ref:
    branch: main
  secretRef:
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: blueprints
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: blueprints
  path: /blueprints/podinfo
  prune: true
  postBuild:
    substituteFrom:
      #
      # https://fluxcd.io/docs/components/kustomize/kustomization/#variable-substitution
      #
      # Keep override order: global variables first, followed by cluster variables last
      - kind: ConfigMap
        name: global-vars
      - kind: ConfigMap
        name: dc-vars
      - kind: ConfigMap
        name: cluster-vars
